export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILED = "GET_USERS_FAILED";
export const GET_USERS_REQUESTED = "GET_USERS_REQUESTED";
export const GET_CHALLENGES = "GET_CHALLENGES";
export const GET_CHALLENGES_SUCCESS = "GET_CHALLENGES_SUCCESS";
export const GET_CHALLENGES_FAILED = "GET_CHALLENGES_FAILED";
export const GET_CHALLENGES_REQUESTED = "GET_CHALLENGES_REQUESTED";
    